export const RESPONSE = 'RESPONSE';
export const REQUEST = 'REQUEST';
export const LEDGER_HW_DEVICE_EVENT = 'LEDGER_HW_DEVICE_EVENT';
export const IPC_LEDGER_CHANNEL = {
  NAME: 'IPC_LEDGER_CHANNEL',
  TYPE: {
    SIGN_MSG: 'SIGN_MSG',
    GET_SIGNED_TRANSACTION: 'GET_SIGNED_TRANSACTION',
    GET_IS_INSIDE_APP: 'GET_IS_INSIDE_APP',
    GET_CONNECTED_DEVICES: 'GET_CONNECTED_DEVICES',
    GET_PUB_KEY: 'GET_PUB_KEY',
  }
};
